### ISSUE TITLE
Consolidate configuration per environment

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#121]
Following https://github.com/mozilla/jira-bugzilla-integration/pull/111#discussion_r921997776

>>> I guess it would imply having a config.local.yaml. But it would be better than having the devtest action used in unit tests in config.nonprod.yaml
Member Author
>>>
>> @[grahamalama](https://github.com/grahamalama) grahamalama [4 days ago](https://github.com/mozilla/jira-bugzilla-integration/pull/111#discussion_r922205997)
>> Yeah, maybe this warrants an issue to decide what we want to do here. Feels like we need to account for our different environments (for development, nonprod, and prod) and decide what will be different about each environment
Member
>>
> @[bsieber-mozilla](https://github.com/bsieber-mozilla) bsieber-mozilla [15 hours ago](https://github.com/mozilla/jira-bugzilla-integration/pull/111#discussion_r923723738)
> Alternatively, we opt for one config and make the chosen environments a configuration parameter.
> 
> Then the local/nonprod/prod actions would be in a consolidated yaml but enabled/disabled through whichever parameter. (Boolean flag per environment, list of all environments, etc?)

# Option #1 : add a local config

- `config/config.local.yaml`
- `config/config.nonprod.yaml`
- `config/config.prod.yaml` 

# Option #2 : add an `environments` field to action config

```yaml
    whiteboard_tag: example
    contact: example@allizom.com
    description: example configuration
    module: src.jbi.whiteboard_actions.default
    environments: ['nonprod', 'prod']
    parameters:
      jira_project_key: EXMPL
```
