### ISSUE TITLE
Add Firefox Android Team Tag (FXDROID)

### ISSUE THREAD

**Issue by cpeterso** [mozilla/jira-bugzilla-integration#301]
The Firefox Android team would like to set up JBI sync from Bugzilla to our [FXDROID Jira project](https://mozilla-hub.atlassian.net/plugins/servlet/project-config/FXDROID/summary). The Android team will typically work in the `Fenix`, `Focus`, and `GeckoView` Bugzilla products, but it would be nice if we could also sync Bugzilla bugs in other products (such as `Core`).

Something like this untested code:

```
whiteboard_tag: fxdroid
  contact: cpeterson@mozilla.com
  description: Firefox Android Team Tag
  enabled: true
  parameters:
    jira_project_key: FXDROID
   steps:
      new:
      - create_issue
      - maybe_delete_duplicate
      - add_link_to_bugzilla
      - add_link_to_jira
      - maybe_assign_jira_user
      - maybe_update_issue_resolution
      - maybe_update_issue_status
      existing:
      - update_issue
      - maybe_assign_jira_user
      - maybe_update_issue_resolution
      - maybe_update_issue_status
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      RESOLVED: Closed
      REOPENED: In Progress
      VERIFIED: Closed
    resolution_map:
      FIXED: Fixed
      INVALID: Won't Do
      WONTFIX: Won't Do
      INACTIVE: Won't Do
      DUPLICATE: Duplicate
      WORKSFORME: Cannot Reproduce
      INCOMPLETE: Won't Do
      MOVED: Duplicate
```

1. I think I may be trying to use Jira status and resolution incorrectly. IIUC, the [FXDROID Jira project](https://mozilla-hub.atlassian.net/plugins/servlet/project-config/FXDROID/summary) has separate `Done` and `Cancelled` status values, but maybe `Cancelled` is redundant and we should use the `Done` status with a resolution like "Won't Do" and "Duplicate"?

2. What are the default `steps` for `new`, `existing`, and `comment`? Do nothing?

3. Is it possible to set the Jira issue type based on the Bugzilla bug type (`defect`, `enhancement`, `task`)?

![image](https://user-images.githubusercontent.com/629193/198152567-c5ef0f02-51e5-4c29-8889-eef91aab6a24.png)

If it’s not possible, that’s OK; it's not a big deal. If it is possible, I’d like to map Bugzilla bug types to Jira issue types like this:

```
  defect: Bug
  enhancement: Task
  task: Task
```
