### ISSUE TITLE
Set up Sentry Releases?

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/jira-bugzilla-integration#384]
https://github.com/marketplace/actions/sentry-release

https://docs.sentry.io/platforms/python/configuration/releases/#release-health

Provides data for additional dashboards in Sentry:
<img width="676" alt="Screenshot 2023-02-01 at 3 40 20 PM" src="https://user-images.githubusercontent.com/53873986/216192712-317a508b-6822-4d79-8d82-2590aa4257ed.png">

"PROD" Releases:
```
name: Create releases

on:
  release:
    types: [published]
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      
jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: prod
```

Sentry "STAGE" Releases:
```
name: Create staging release for Sentry

on:
  push:
    branches:
      - main


jobs:
  create-sentry-release-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: stage
```
