### ISSUE TITLE
Provide ability to link Bugzilla `severity` field to a Jira field

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#464]

**Comment by leplatrem** [comment]
Could it be a `maybe_update_severity` step with parameters like?

```
- whiteboard_tag: sp3
  bugzilla_user_id: 396948
  description: Speedometer 3
  parameters:
    jira_severity_field: severity
    jira_severity_map:
      S1: Very bad
      S2: Bad
      S3: Important
      S4: Not important
      N/A: Unknown
```
