### ISSUE TITLE
How to extend existing actions?

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#77]
In #75 we are adding more logic to the default action behavior. Namely setting assignee and status fields.

The chosen approach was to extend the default action behavior using inheritance.

**Pros**

- No duplicated code between actions

**Cons**

- Indirection. One has to read and mentally merge two classes in order to understand the final behavior
- Hard to pick (eg. I want status to be set, but not the assignee)

There could be other approaches to consider:

## Single action with (many) parameters

```yaml
    action: src.jbi.whiteboard_actions.default_action
    contact: [example@allizom.com]
    description: example configuration
    enabled: true
    parameters:
      jira_project_key: EXMPL
      whiteboard_tag: example
      sync_assignee: True
      status_map:
        NEW: "In Progress"
        FIXED: "Closed"
```

**Pros**

- A single piece of code to read  (`default_action.py`)

**Cons**

- The default action code could potentially grow indefinitely, and we would loose the extensibility offered by the action API
- Unit tests have to combine a lot of combinations for the parameters

## Support execution of multiple atomic actions

Instead of a single action, define a list of actions to be executed. The specified parameters would be passed to all to simplify configuration.

```yaml
    contact: [example@allizom.com]
    description: example configuration
    enabled: true
    actions:
       - src.jbi.whiteboard_actions.create_or_update
       - src.jbi.whiteboard_actions.comments
       - src.jbi.whiteboard_actions.assignee
       - src.jbi.whiteboard_actions.status
    parameters:
      jira_project_key: EXMPL
      whiteboard_tag: example
      status_map:
        NEW: "In Progress"
        FIXED: "Closed"
```

**Pros**

- Smaller bits of code
- Modularity
- Easier testing

**Cons**

- Potential duplication in config if all use-cases want the same set of actions
- Multiple calls to API for separate fields (verbose history in jira?)

----

There could be other approaches. Maybe the current one is fine, but at least this issue could help us drive a conversation about it (before the code would grow too much)
